class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        to_check=set(t)
        for element in to_check:
            if s.count(element) != t.count(element):
                return element
    
    
    
    
solution=Solution()
s="xpmssbwloowxibtwvhabflaoqgoyswznxepaoevvqohhamkucbcfsonazfnmcoqechnyigsbuvzrligprykurwahetwjmdknmearurflryhligaptsdqrlgapoyzocwwnavcsdiuqpbzmedzsvifcqzjjqqjshqmxczobymhwwiojfcvfjvaygupgacyvhnckmdasgspxoijltxebfspwlpjbzpoonalwujttowlsiagmcgfqwxoznuehztvuvpgzrvrjnybfcolufwgwsgmuxdqfgcisxgeibinqxacrtwznwvmxximhhhdehxrftpcczubiabgkbscrundidaqzcbmzpiqecfruiffzuajxjnnwipeivtswffizywisuvhkkcjwgxazntusebfbaawflsazleudgmhyzgfspyqmqanozvksrougiypcmiokgdhmkwyngmrynkekfjogjpgannxdtczvgxmatirlfcsphzouosyknxigetrpzudjaxcepvdfmqfyjpvxifntszpbzfkrlxgodjecpvtljolottyhaonpvatwhynicfusbrcnfhkpglaouhmljaavvguoiyiynpqykhaqsbbdroszpawpzgjtnzmqeiuvbwhyphrhqzbaqnnusbiopkzbsovqtykfioyurtqqnspkhnllmsvkgewpslshrambdokxhrelsehvvgitcwyrhivarxjagtsgfnhudizcbmvncgjfa"
t="wsxqlutrifhyejgmohyvlkjobelupizpgbgavnltzspgvmthdhioonnilqshpsvyejddnitnxrpmdvkudqhoajzupcxrwghhyhudsqrszojzwpcbontwdbfbqncysqzgoayjxbqkieamizzsoaqksqwjmjawwmkltcfzffruhaarhcexhenrgizwvnqfkrfhthbovxuynxoltrtagsceiiphsombaqcztfookpepwymnsxtlspgbdkmyezlzdvinemwibvsggnyfoabsfqxtgzecfiwpyqzsiilnrmugnbczsouczgfmkhunqfhpzqgyurrzpqccmvfjnbwgwrlclnvvsgbhkdfipnsinmasvryegdzuiazoisrcbgpyohvhvpujjxxtoruxpomxmjwuockcwjgpnhlfojvapaxnablqhujdtsofuiapfcjcdvxsavkavmrptqptpnxaasazuolwcltbysmezytwvmzislbasghogaqhhjqryzmbubsewcyustwguyiyvgswcefbpgrzjgvwezzmzfatatksonevbcupwtoxcjxaivqxciuklycbacoonuvvmuaazmrgguiuzyrhjbipwjpurofecklonpldgofikgijfiknaqisrmxfnvlqbwwifykjogtdqocdpffetagavwrchfiskwwecmrhhnpvlifaxkhbdapyafighonnxeamgpqnazvsnkbzrdcwyfyssseagfhlixn"

print(solution.findTheDifference(s,t))